parameters:
  vmImage: ubuntu-16.04
  toolchain: stable
  cmd: test

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
    - template: azure-install-rust.yml
      parameters:
        toolchain: ${{ parameters.toolchain }}

    - ${{ if not(eq(parameters.cmd, 'test')) }}:
      - script: |
          cargo ${{ parameters.cmd }} --all --no-default-features
          cargo ${{ parameters.cmd }} --all
        displayName: cargo ${{ parameters.cmd }}

    - ${{ if eq(parameters.cmd, 'test') }}:
      - script: |
          cargo ${{ parameters.cmd }} --all --tests --no-default-features
          cargo ${{ parameters.cmd }} --all --tests
        displayName: cargo ${{ parameters.cmd }} --tests

    - ${{ if eq(parameters.toolchain, 'nightly') }}:
      - script: |
          cargo ${{ parameters.cmd }} --all --all-features
        displayName: cargo ${{ parameters.cmd }} --all-features

      # Refs: https://github.com/rust-lang/cargo/issues/5657
      - script: |
          cargo update -Zminimal-versions
          cargo check --all --all-features
        displayName: cargo check -Zminimal-versions
