parameters:
  cmd: test

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }} ${{ parameters.rust }}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04

      ${{ if parameters.cross }}:
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)

  steps:
    - template: azure-install-rust.yml
      parameters:
        rust: ${{ parameters.rust }}

    - ${{ if not(eq(parameters.cmd, 'test')) }}:
      - script: |
          cargo ${{ parameters.cmd }} --all --no-default-features
          cargo ${{ parameters.cmd }} --all
        displayName: cargo ${{ parameters.cmd }}

    - ${{ if eq(parameters.cmd, 'test') }}:
      - script: |
          cargo ${{ parameters.cmd }} --all --tests --no-default-features
          cargo ${{ parameters.cmd }} --all --tests
        displayName: cargo ${{ parameters.cmd }} --tests

    - ${{ if eq(parameters.rust, 'nightly') }}:
      - script: |
          cargo ${{ parameters.cmd }} --all --all-features
        displayName: cargo ${{ parameters.cmd }} --all-features

      - script: |
          cargo update -Zminimal-versions
          cargo check --all --all-features
        displayName: cargo check -Zminimal-versions
