jobs:
- job: ${{ parameters.name }}
  displayName: compile-test
  pool:
    vmImage: ubuntu-16.04

  steps:
    - template: azure-install-rust.yml
      parameters:
        rust: ${{ parameters.rust }}

    - script: |
        cargo clean
        RUSTFLAGS='--cfg ui_tests' cargo test -p auto_enums --all-features --test compile-test
      displayName: cargo test (compile-test)
