jobs:
- job: ${{ parameters.name }}
  displayName: compiletest
  pool:
    vmImage: ubuntu-16.04

  steps:
    - template: azure-install-rust.yml
      parameters:
        rust: ${{ parameters.rust }}

    - script: |
        cargo clean
        RUSTFLAGS='--cfg compiletest' cargo test -p auto_enums --all-features --test compiletest
      displayName: compiletest
