name: ci

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
  schedule:
    - cron: 00 01 * * * # Daily

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      matrix:
        rust:
          # This is the minimum Rust version supported by auto_enums.
          # When updating this, the reminder to update the minimum supported
          # Rust version in README.md.
          #
          # Tests are not run as tests may require newer versions of Rust.
          - 1.31.0
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          set -e
          rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: cargo check
        if: matrix.rust == '1.31.0'
        run: |
          cargo check --all --no-default-features
          cargo check --all
          cargo check --features type_analysis
      - name: cargo test
        if: matrix.rust != '1.31.0'
        run: |
          cargo test --all --tests --no-default-features
          cargo test --all --tests
          cargo test --tests --features type_analysis
      - name: cargo test --all-features
        if: matrix.rust == 'nightly'
        run: |
          cargo test --all --all-features
      - name: cargo test --cfg auto_enums_def_site_enum_ident
        if: matrix.rust == 'nightly'
        run: |
          cargo test --all --all-features -- -Zunstable-options --include-ignored
        env:
          RUSTFLAGS: -Dwarnings --cfg auto_enums_def_site_enum_ident
      - name: cargo check --benches
        if: matrix.rust == 'nightly'
        run: |
          cargo check --benches
      # Refs: https://github.com/rust-lang/cargo/issues/5657
      - name: cargo check -Zminimal-versions
        if: matrix.rust == 'nightly'
        run: |
          cargo update -Zminimal-versions
          cargo check --all --all-features

  style:
    name: style
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      fail-fast: false
      matrix:
        component:
          - clippy
          - rustfmt
          - rustdoc
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          set -e
          rustup update nightly && rustup default nightly
      - name: Install component
        if: matrix.component != 'rustdoc'
        run: |
          set +e
          if rustup component add ${{ matrix.component }}; then
            set -e
          else
            set -e
            # If the component is unavailable on the latest nightly,
            # use the latest toolchain with the component available.
            # Refs: https://github.com/rust-lang/rustup-components-history#the-web-part
            component=${{ matrix.component }}
            target=`curl https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/$component`
            echo "'$component' is unavailable on the toolchain 'nightly', use the toolchain 'nightly-$target' instead"
            rustup toolchain install nightly-$target
            rustup default nightly-$target
            rustup component add $component
          fi
      - name: cargo clippy
        if: matrix.component == 'clippy'
        run: |
          cargo clippy --all --all-features
      - name: cargo fmt -- --check
        if: matrix.component == 'rustfmt'
        run: |
          cargo fmt --all -- --check
      - name: cargo doc
        if: matrix.component == 'rustdoc'
        run: |
          cargo doc --no-deps --all --all-features
        env:
          RUSTDOCFLAGS: -Dwarnings
